export const genreMap = {
  House: ['deep-house', 'progressive-house', 'tropical-house'],
  Techno: ['techno', 'minimal-techno'],
  Indie: ['indie-pop', 'indie-rock'],
  HipHop: ['hip-hop', 'rap'],
  Electronic: ['electronic', 'electro'],
  Pop: ['pop'],
  Rock: ['rock'],
  Afrobeat: ['afrobeat'],
  Latin: ['latin'],
  Jazz: ['jazz'],
  'Funk & Soul': ['funk', 'soul'],
  Ambient: ['ambient'],
  Experimental: ['experimental'],
};
